---
- name: Setup Elk Server
  hosts: elk
  become: true
  tasks:
    - name: Install docker
      apt:
        force_apt_get: yes
        name: docker.io
        state: present
        update_cache: yes
    - name: Install python3
      apt:
       name: python3-pip
       state: present
       update_cache: yes
       force_apt_get: yes
    - name: Install docker python
      pip:
        name: docker
        state: present
    - name: Increase virtual memory
      command: sysctl -w vm.max_map_count=262144
    - name: use more memory on restart
      sysctl:
        name: vm.max_map_count
        value: 262144
        state: present
        reload: yes
    - name: download and launch a container of Elk
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044
